name: Laravel Pint

on: [push, pull_request]

jobs:
  pint:
    name: Run Laravel Pint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Adjust to match your Laravel version
          tools: composer

      - name: Add Flux Credentials Loaded From ENV
        run: composer config http-basic.composer.fluxui.dev "${{ secrets.FLUX_USERNAME }}" "${{ secrets.FLUX_LICENSE_KEY }}"

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Run Laravel Pint
        run: ./vendor/bin/pint --test